version: "2.1"

services:
  elasticnode:
    image: elasticnode
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
        - ELASTIC_URL=http://elasticsearch:9200
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch
    networks:
      - esnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - esnet
networks:
  esnet:
