http:
  port: 8100
admin:
  port: 9876
apiEndpoints:
  api:
    host: "*"
    paths: "/ip"
  gameguide:
    host: "*"
    paths: ["/api/gameguide", "/api/gameguide/*"]
  elastic:
    host: "*"
    paths: ["/search", "/search/*"]
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  gameguideService:
    url: "http://nodeexpressmongodb:8200"
  elasticService:
    url: "http://elasticnode:9000"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  gameguidePipelines:
    apiEndpoints:
      - gameguide
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: gameguideService
              changeOrigin: true
  elasticPipelines:
    apiEndpoints:
      - elastic
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: elasticService
              changeOrigin: true
