http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  tutorial:
    host: localhost
    paths: ["/api/tutorials", "/api/tutorials/*"]
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  tutorialsService:
    url: "http://192.168.99.100:8080"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  tutorialsPipelines:
    apiEndpoints:
      - tutorial
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: tutorialsService
              changeOrigin: true
