version: "3.4"

services:
  nodeexpressmongodb:
    image: nodeexpressmongodb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8200:8200
    volumes:
      - .:/usr/src/app
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
