version: '3.4'

services:
  expressgateway:
    image: expressgateway
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8100:8100
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
