version: "3.4"

services:
  expressgateway:
    image: expressgateway
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8100:8100
